### ISSUE TITLE
wowjsDelay, wowjsDuration, wowjsAnimation doesn't have a default value

### ISSUE THREAD

**Issue by tim5chneider** [inspiredminds/contao-wowjs#1]
After Installation, its not possible to create new Content elements:

`An exception occurred while executing 'INSERT INTO tl_content [...] SQLSTATE[HY000]: General error: 1364 Field 'wowjsDelay' doesn't have a default value`

So all 3 Fields wowjsDelay, wowjsDuration and wowjsAnimation doesn't have a default value.
After set NULL to all as Standard in tl_content there are no more errors.

**Comment by fritzmg** [comment]
Thx for reporting :)

**Comment by tim5chneider** [comment]
Thx for the plugin :)

**Comment by fritzmg** [comment]
fixed in a7632ed
