### ISSUE TITLE
Deinstallation wow error

### ISSUE THREAD

**Issue by pbd-kn** [inspiredminds/contao-wowjs#11]
Nach der deinstallation über den Contao-Manager kommt der Error

Could not find template "js_wowjs"

Danach ist die Seite nicht mehr benutzbar.
Neuistallation von wow behebt den Fehler, aber ich will die extension völlig weg haben

**Comment by fritzmg** [comment]
That is normal. You will need to disable the template manually. There is no mechanism in Contao to do that automatically (upon deinstallation).

**Comment by pbd-kn** [comment]
Und wie geht das manuell, würde ich ja gerne machen, aber weiß nicht wie

**Comment by fritzmg** [comment]
You just need to disable the template in your layout (where you enabled it before).

**Comment by pbd-kn** [comment]
Danke vielmals. Hat funktioniert.
