### ISSUE TITLE
Headline Content Elements have no effect

### ISSUE THREAD

**Issue by tim5chneider** [inspiredminds/contao-wowjs#2]
Set an Animation to a Headline Content Element (Test with H1 and H2) has no effect.
There is no wow/animation injection in HTML.

**Comment by fritzmg** [comment]
Hm, interesting. In theory it should work with headline elements too, since I am trying to set the CSS classes in any opening HTML tag: https://github.com/inspiredminds/contao-wowjs/blob/1.0.3/src/EventListener/HookListener.php#L43-L64

I'll have a look.
