### ISSUE TITLE
Contao 4.13-RC1

### ISSUE THREAD

**Issue by Seefahrer** [inspiredminds/contao-wowjs#5]
Frontend becomes unreachable with errormessage:

`request.CRITICAL: Uncaught PHP Exception TypeError: "strlen(): Argument #1 ($str) must be of type string, int given" at /Users/georg/Websites/cmsc4ME/vendor/inspiredminds/contao-wowjs/src/EventListener/HookListener.php line 49 {"exception":"[object] (TypeError(code: 0): strlen(): Argument #1 ($str) must be of type string, int given at /Users/georg/Websites/cmsc4ME/vendor/inspiredminds/contao-wowjs/src/EventListener/HookListener.php:49)"} []`

**Comment by fritzmg** [comment]
Please test `dev-master` and see if that fixes the problem.

**Comment by Seefahrer** [comment]
Perfect! Your revised `/vendor/inspiredminds/contao-wowjs/src/EventListener/HookListener.php:49` in `dev-master` works fine now.

**Comment by fritzmg** [comment]
Released as `1.1.4` 👍
