### ISSUE TITLE
Contao 4.13 no js_wowjs

### ISSUE THREAD

**Issue by pbd-kn** [inspiredminds/contao-wowjs#9]
In meinem Layout gibt es keine Auswahl de scripts   js_wowjs

Was mache ich falsch

![grafik](https://github.com/inspiredminds/contao-wowjs/assets/75879364/c554717d-b2a4-413b-8ede-65c982607f34)

**Comment by fritzmg** [comment]
Your screenshot does not show the right section.

**Comment by pbd-kn** [comment]
Mehr habe ich nicht, oder was meinst du
LG
Peter

![grafik](https://github.com/inspiredminds/contao-wowjs/assets/75879364/583348a6-f2f9-48ad-974e-bfd15dc5683c)
![grafik](https://github.com/inspiredminds/contao-wowjs/assets/75879364/09470523-1ac0-46f3-9542-0e4127448c26)
![grafik](https://github.com/inspiredminds/contao-wowjs/assets/75879364/e6f5ab32-6f5a-40bb-89fc-a504bae9090f)
![grafik](https://github.com/inspiredminds/contao-wowjs/assets/75879364/1e1a4d1b-c291-4280-aeb1-27ca47c819f4)

**Comment by fritzmg** [comment]
Your Contao installation is missing the following section:

<img src="https://github.com/inspiredminds/contao-wowjs/assets/4970961/18c840a7-14be-4b29-8b89-13e5bda2a580" width="314">

This is likely caused by an extension or app adjustment on your side.

Also you should be careful with your screenshots ... ;)

**Comment by pbd-kn** [comment]
Das ist mir schon klar, aber ich weiß nicht warum bei mir diese section im Layout niccht vorhanden ist

**Comment by fritzmg** [comment]
I cannot help you there. It has nothing to do with this extension.

**Comment by pbd-kn** [comment]
ok dann muss ich suchen
Danke für die schnelle Antwort
